version: "3"
services:
   #PHP Service
   database:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9906:3306"
    networks:
       - nginx-proxy
    

   fuzonapi:
     build:
      context: .
      dockerfile: Dockerfile
     image: fuzonmedia/fuzonapi
     restart: unless-stopped
     ports:
       - "8080:80"
     
     volumes:
       - ./:/var/www/html
     working_dir: /var/www/html
     container_name: fuzonapi
     networks:
       - nginx-proxy

networks:
  nginx-proxy:
    external: true